# In a DNA string, the complement of A is T, and the complement of C is G.
#
# The reverse complement of a DNA string s is the string sc formed by reversing the symbols
# of s, then taking the complement of each symbol (e.g., the reverse complement of GTCA is
# TGAC).
#
# Given: A DNA string s of length at most 1000 bp.
#
# Return: The reverse complement of s.
#
# Sample Dataset
#
# AAAACCCGGT
#
#Sample Output
#
# ACCGGGTTTT

complement = {'A': 'T',
              'C': 'G',
              'G': 'C',
              'T': 'A'}

def reverse_complement(dna):
    reverse = dna[::-1]
    return ''.join([complement[nucleotide] for nucleotide in reverse])

assert reverse_complement('AAAACCCGGT') == 'ACCGGGTTTT'

dna = "CGGGTCAAAAGAATCCCACCGTGTGCTAGCCTCGGCTCTTCTGCCTAACGAAGCTTTACATCCAGCATTAAGAATCTCCTATGAACAGCATGACCTCGAGAGTCATTTCATTAGTTGGAATATCGTAGTGTACGGTTTTGACAATGTGGAGTAGCCCGGTGCTGGTAACAACGCCAGTGTGGTAGGCTAGGCACCGTTTATAATGACGATCAGGGCACTATCCAGGTTACTGCTTTGGGCATGGTAGACGACTCGATGCAGCCTTCACGCACCAACATCTATTTCAGGCACGTGAGAGTGTTCTATAATAATAAGTCGGTGCCGAGGGTCTTAAGGATAAACATTTTAAAGGCAGGGTATCCACCTTGATTTATGTGGAATATCTGCTGCTTGGGGCAGCTCTGGTCATGACTCCGGGCCTCAAACGCCGCGACCAGTGACTTTGGAGCGCTTGGCAGTTATATGAACCTTGCATCAGCCCGCGATTGCCATATTTGCATAATCTGGATTTAATTCCCCGCCAGTTATGAGGAAGGCTACTCTAGCTGCATGACCTAACCCAACCACCAACACTGCAATGCGTAGCTCGCCGGCAAGTGTACAGTCGACAACGGACACGCCTTCCTGTGTCCTGAGACCTCCGGTCCTTGCTATCTTAGATAGACCAGGGACTAAATGTGGGGTAGGTTACTAAAGCAGGGACTTACTCCGACGCACCCTTCTGATGGAGTGAATCGTCCGTGTAAATGGGACGCGAGCTAACTGTACATGTGGTTAGCCGGGAGTTTGGTGGATTGTATTTGCATTCCCCCTGAAGGCGTGCCTAAATACGAAAAACGGGTGGAGCTATGCCCTAAAATCAAGCAGCAGACCTAAAGCATTCTTGGGCCGCACCACCAGATGGCTATTGTTATCTGAGTTGATTCGACTGTCCAATTACCCCGGCGCAAGGGATAAGCATAACTCTATCATTATCAAGATG"
    
revc1 =  reverse_complement(dna)

## Biopython

from Bio.Seq import Seq

dna = Seq("CGGGTCAAAAGAATCCCACCGTGTGCTAGCCTCGGCTCTTCTGCCTAACGAAGCTTTACATCCAGCATTAAGAATCTCCTATGAACAGCATGACCTCGAGAGTCATTTCATTAGTTGGAATATCGTAGTGTACGGTTTTGACAATGTGGAGTAGCCCGGTGCTGGTAACAACGCCAGTGTGGTAGGCTAGGCACCGTTTATAATGACGATCAGGGCACTATCCAGGTTACTGCTTTGGGCATGGTAGACGACTCGATGCAGCCTTCACGCACCAACATCTATTTCAGGCACGTGAGAGTGTTCTATAATAATAAGTCGGTGCCGAGGGTCTTAAGGATAAACATTTTAAAGGCAGGGTATCCACCTTGATTTATGTGGAATATCTGCTGCTTGGGGCAGCTCTGGTCATGACTCCGGGCCTCAAACGCCGCGACCAGTGACTTTGGAGCGCTTGGCAGTTATATGAACCTTGCATCAGCCCGCGATTGCCATATTTGCATAATCTGGATTTAATTCCCCGCCAGTTATGAGGAAGGCTACTCTAGCTGCATGACCTAACCCAACCACCAACACTGCAATGCGTAGCTCGCCGGCAAGTGTACAGTCGACAACGGACACGCCTTCCTGTGTCCTGAGACCTCCGGTCCTTGCTATCTTAGATAGACCAGGGACTAAATGTGGGGTAGGTTACTAAAGCAGGGACTTACTCCGACGCACCCTTCTGATGGAGTGAATCGTCCGTGTAAATGGGACGCGAGCTAACTGTACATGTGGTTAGCCGGGAGTTTGGTGGATTGTATTTGCATTCCCCCTGAAGGCGTGCCTAAATACGAAAAACGGGTGGAGCTATGCCCTAAAATCAAGCAGCAGACCTAAAGCATTCTTGGGCCGCACCACCAGATGGCTATTGTTATCTGAGTTGATTCGACTGTCCAATTACCCCGGCGCAAGGGATAAGCATAACTCTATCATTATCAAGATG")

revc2 =  str(dna.reverse_complement())

assert revc1 == revc2
